---
title: "Condathis: Run Any CLI Tool"
vignette: >
  %\VignetteIndexEntry{condathis}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---

```{r}
#| label: setup
library(condathis)
```

When we say run any CLI tool reproducibly, we mean it.
With `condathis`, you can run any command-line interface (CLI) tool within a
specified Conda environment, ensuring that the tool's dependencies are managed
and isolated.

## Internet Cat Gifs

Are you sure you don't want to see some internet cat gifs here?

```{r}
#| label: cat_gifs
# ggplot2 exampel on hold, not a suggest dependency yet.
# library(ggplot2)

# Create a simple plot
# ggplot(mtcars, aes(x = wt, y = mpg)) +
#  geom_point() +
#  theme_minimal()
```

## Base Plot Cat

```{r}
#| label: base_plot_cat
#| fig.width: 5
#| fig.height: 5
#| fig.align: center

plot(
  x = 0, y = 0,
  type = "n",
  xlim = c(-3, 3),
  ylim = c(-3, 3),
  asp = 1,
  xlab = "",
  ylab = "",
  main = "Cat Shape in R"
)

# Two semicircles for the head
curve(
  sqrt(4 - x^2),
  from = -2, to = 2,
  col = "black", lwd = 2,
  add = TRUE
)
curve(
  -sqrt(4 - x^2),
  from = -2, to = 2,
  col = "black", lwd = 2,
  add = TRUE
)

# Left ear
segments(
  x0 = -1.75, y0 = 1,
  x1 = -1.2, y1 = 3,
  col = "black", lwd = 2
)
segments(
  x0 = -1.2, y0 = 3,
  x1 = -0.2, y1 = 2,
  col = "black", lwd = 2
)

# Right ear
segments(
  x0 = 0.2, y0 = 2,
  x1 = 1.2, y1 = 3,
  col = "black", lwd = 2
)
segments(
  x0 = 1.2, y0 = 3,
  x1 = 1.75, y1 = 1,
  col = "black", lwd = 2
)

# Eyes
points(x = c(-0.8, 0.8), y = c(0.5, 0.5), pch = 16, cex = 2, col = "gray30")
points(
  x = c(-0.85, 0.75), y = c(0.48, 0.48),
  pch = 16, cex = 0.6, col = "white"
)
# Nose (triangle)
points(x = 0, y = -0.5, pch = 17, cex = 1.5, col = "gray10")
points(x = 0, y = -0.5, pch = 17, cex = 1.35, col = "lightpink")

# Mouth
curve(
  expr = {
    -0.5 * sqrt(1 - (x / 1)^2) - 1
  },
  from = -0.25, to = 0.25,
  col = "black", lwd = 2,
  add = TRUE
)
```
